export enum EGPSStatus {
    CONNECTED = 'CONNECTED',
    ERROR_NOT_FOUND = 'ERROR_NOT_FOUND',
    ERROR_INVALID_DEVICE = 'ERROR_INVALID_DEVICE',
    ERROR_UNAVAILABLE = 'ERROR_UNAVAILABLE',
    OFFLINE = 'OFFLINE',
}